spring.application.name=Authentication

spring.output.ansi.enabled=ALWAYS

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=jdbc:mysql://localhost:3306/auth
spring.datasource.username=root
spring.datasource.password=tiger
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

JWT_SECRET=10ccf6ca7a7e8b7ae52860580b6d87ef65fb292133748be1220888a2566e0649
JWT_EXPIRATION_MS=7d

spring.security.oauth2.client.registration.google.client-id=66555713864-7brgqal3e9hbqthv3s0oeij2ncu7ge5a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
