spring.application.name=Api_Gateway

server.port=8086

ai_service.url=http://localhost:5001


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600

# ================================
# REDIS
# ================================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=StrongPassword123
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=1

# ================================
# EUREKA
# ================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ================================
# JWT
# ================================
jwt.secret=10ccf6ca7a7e8b7ae52860580b6d87ef65fb292133748be1220888a2566e0649
jwt.expiration=86400000

# ================================
# RATE LIMIT
# ================================
rate-limit.replenish-rate=20
rate-limit.burst-capacity=40

# ================================
# LOGGING
# ================================
logging.level.com.APIGateway.Api_Gateway=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.data.redis=DEBUG

# ================================
# ACTUATOR
# ================================
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true