spring.application.name=BookUpload
server.port=8081

spring.output.ansi.enabled=ALWAYS

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:postgresql://localhost:5432/BookUpload
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Cloudinary
cloudinary.cloud-name=ds8azswqx
cloudinary.api-key=641571155133815
cloudinary.api-secret=7N53PtJhuND6IUbI9I_TRYnJqqk

# Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Tomcat
server.tomcat.connection-timeout=120000
server.tomcat.keep-alive-timeout=120000

# ? Kafka ? THIS is what was causing 66 second hang
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.retries=1
spring.kafka.producer.properties.retry.backoff.ms=500


spring.kafka.producer.properties.max.block.ms=3000
spring.kafka.producer.properties.delivery.timeout.ms=5000
spring.kafka.producer.properties.request.timeout.ms=3000
kafka.topic.book-events=book-events-topic


