spring.application.name=BookUpload
server.port=8081

spring.output.ansi.enabled=ALWAYS

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:postgresql://localhost:5432/BookUpload
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud-name= ds8azswqx
cloudinary.api-key=641571155133815
cloudinary.api-secret=7N53PtJhuND6IUbI9I_TRYnJqqk

# ?? Kafka ??????????????????????????????????????????????
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Retry on failure
spring.kafka.producer.retries=3
spring.kafka.producer.properties.retry.backoff.ms=1000

# Topic name
kafka.topic.book-events=book-events-topic